services:
  - type: web
    name: interview-master-backend
    runtime: docker
    dockerfilePath: ./Backend/Dockerfile
    dockerContext: ./Backend
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_GENAI_API_KEY
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: NODE_ENV
        value: production
